# Basic dependabot.yml to update GitHub actions

version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    target-branch: "master"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    reviewers:
      - "rohenaz"
    assignees:
      - "rohenaz"
    labels:
      - "chore"
    open-pull-requests-limit: 10
